### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by appl3s** [gofmt/iOSSniffer#1]
https://github.com/gofmt/iOSSniffer/blob/9571e3ef405c2c2d2540fe451c65af9df1de618c/pkg/sniffer/sniffer.go#L44

请问大佬这个结构体的文档，谢谢啦

**Comment by gofmt** [comment]
> https://github.com/gofmt/iOSSniffer/blob/9571e3ef405c2c2d2540fe451c65af9df1de618c/pkg/sniffer/sniffer.go#L44
> 
> 请问大佬这个结构体的文档，谢谢啦

**Comment by gofmt** [comment]
> https://github.com/gofmt/iOSSniffer/blob/9571e3ef405c2c2d2540fe451c65af9df1de618c/pkg/sniffer/sniffer.go#L44
> 
> 请问大佬这个结构体的文档，谢谢啦

哈哈,这个结构体没有文档,我也是瞎猜的.

**Comment by appl3s** [comment]
好的，参考大佬的研究成果我贡献代码到了这里，我还发现了一些大小端问题（Pid字段）
https://github.com/danielpaulus/go-ios/blob/6e503995c4930768f3028b31bf4d447a07a583f6/ios/pcap/pcap.go#L25

**Comment by gofmt** [comment]
> 好的，参考大佬的研究成果我贡献代码到了这里，我还发现了一些大小端问题（Pid字段）
> https://github.com/danielpaulus/go-ios/blob/6e503995c4930768f3028b31bf4d447a07a583f6/ios/pcap/pcap.go#L25

嘿嘿嘿,我重写了go-ios核心通讯部分.

**Comment by appl3s** [comment]
我去学习一下～～我工作中要用的东西在你这边都能找到
