### ISSUE TITLE
 libfrida-core.a 没找到

### ISSUE THREAD

**Issue by ohyeah521** [gofmt/iOSSniffer#4]
libfrida-core.a 没找到， 我应该下载那个文件呢？

**Comment by gofmt** [comment]
[frida-core-devkit-15.1.20-ios-arm64.tar.xz](https://github.com/frida/frida/releases/download/15.1.20/frida-core-devkit-15.1.20-ios-arm64.tar.xz)

**Comment by ohyeah521** [comment]
感觉回复，把这个文件放到frida目录下，windows环境下编译出错，错误信息如下：
# github.com/gofmt/iOSSniffer/pkg/idevice
..\pkg\idevice\conn_windows.go:3:6: usbmuxdDial redeclared in this block
        ..\pkg\idevice\conn.go:7:6: other declaration of usbmuxdDial
..\pkg\idevice\conn_windows.go:3:21: undefined: net
..\pkg\idevice\conn_windows.go:4:9: undefined: net
# github.com/gofmt/iOSSniffer/pkg/frida
In file included from ..\pkg\frida\frida.go:4:
..\pkg\frida/frida-core.h:34184:1: error: unknown type name 'uid_t'
 uid_t            g_credentials_get_unix_user      (GCredentials    *credentials,
 ^~~~~
..\pkg\frida/frida-core.h:34188:52: error: unknown type name 'uid_t'; did you mean 'pid_t'?
                                                    uid_t           uid,
                                                    ^~~~~
                                                    pid_t

**Comment by gofmt** [comment]
并不支持WIndows
